# Generated by Django 3.2.2 on 2021-05-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDetails',
            fields=[
                ('CourseID', models.IntegerField(primary_key=True, serialize=False)),
                ('CourseTitle', models.CharField(max_length=500)),
                ('CourseName', models.TextField()),
                ('CourseSectionCode', models.CharField(max_length=500)),
                ('CourseDepartment', models.CharField(max_length=500)),
                ('InstructorFullName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('StudentID', models.IntegerField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Major', models.CharField(max_length=100)),
                ('Year', models.CharField(max_length=50)),
                ('GPA', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentName', models.CharField(max_length=500)),
                ('CourseName', models.CharField(max_length=500)),
            ],
        ),
    ]
